### ISSUE TITLE
Скраперы

### ISSUE THREAD

**Issue by Vanuan** [open-budget/data#55]
Как насчет скраперов? Не вижу их в репозитории.
Вот тут кой-чо написал:
https://github.com/Maidan-hackaton/budget

**Comment by grsmv** [comment]
Ідея чудова, але на практиці стикається з тотальною нестандартизованістю представлення даних різними ОДА. Одні полюбляють додатки до законів "Про обласний бюджет на ХХХ рік" розміщувати у doc, інші у pdf, інші є магістрами екселю і використовують його, але знов-таки, як доля на душу покладе. Тобто вийнятків буде більше ніж правил і я, власне, порахував що  зробити руками буде значно швидше. Особливо приймаючи до уваги, що це 25 документів на рік.

**Comment by Vanuan** [comment]
Ценность подобного ПО и есть в автоматизации сбора. Ибо невозможно потом доказать, что не было ошибки при наполнении вручную.
Документов не 25, ты не учитываешь, что в документы вносятся изменения.
А если учесть отчеты о выполнении бюджетов за каждый месяц, то получается 300 документов.
И еще: почему только 25? Бюджеты облцентров и городов областного значения независимы от ОДА.

**Comment by Vanuan** [comment]
Машиночитаемый вид будет:
http://etransformation.org.ua/2014/12/23/464/
Но это не означает стандартизацию. Приводить к различным форматам все равно надо будет, даже мы добьемся csv.
Сперва нужно собрать источники информации.

**Comment by grsmv** [comment]
О, дуже круто. Будемо слідкувати за розвитком виконання даного закону. Дякую!

**Comment by Vanuan** [comment]
Порівняльна таблиця:
http://www.minregion.gov.ua/attachments/content-attachments/3733/%D0%9F%D0%BE%D1%80%D1%96%D0%B2%D0%BD%D1%8F%D0%BB%D1%8C%D0%BD%D0%B0%20%D1%82%D0%B0%D0%B1%D0%BB%D0%B8%D1%86%D1%8F.pdf
