### ISSUE TITLE
Коды регионов -> КОАТУУ

### ISSUE THREAD

**Issue by Vanuan** [open-budget/data#56]
Вместо кодов регионов предлагаю использовать коды КОАТУУ:
http://data-gov-ua.org/dataset/koatuu

**Comment by grsmv** [comment]
Так, дуже слушна думка. Якось можна поправити кодировки? Utf-8?

**Comment by grsmv** [comment]
Ок, знайшов у корректній кодировці - http://data-gov-ua.org/dataset/koatuu/resource/faef96db-5bca-4af1-9f19-f8c2e6d5a174
Воно ще актуальне?

**Comment by grsmv** [comment]
Дуже слушна думка. Наскільки коректним буде використання змердженого з чотирьох рівнів коду? Тобто "0100000000" замість "01 000 000 00"  ?

**Comment by Vanuan** [comment]
Якщо планується тільки регіональний рівень, достатньо [двох цифр](http://data-gov-ua.org/dataset/koatuu/resource/1a5d811b-9877-46a0-8f27-5c3777f6ed46).
Якщо ж є більш амбіційні плани, тоді так, треба використовувати повний код.
Використанння змержденого коду є цілком корректним. Розбиття корисне, щоб показати ієрархію або щоб сортувати за рівнем (спочатку 1-го рівня, потім 2-го рівня і т.п.).

**Comment by grsmv** [comment]
Супер. Дякую!

**Comment by grsmv** [comment]
Перенесено в https://github.com/open-budget/api/issues/32
